// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace InvSys.StockQuotes.Api.Client.Proxy.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CurrentQuote
    {
        /// <summary>
        /// Initializes a new instance of the CurrentQuote class.
        /// </summary>
        public CurrentQuote() { }

        /// <summary>
        /// Initializes a new instance of the CurrentQuote class.
        /// </summary>
        public CurrentQuote(string symbol = default(string), string name = default(string), double? latestTradePrice = default(double?), double? eps = default(double?), double? epsEstimateCurrentYear = default(double?), double? epsEstimateNextYear = default(double?), double? peRatio = default(double?), double? pegRatio = default(double?))
        {
            Symbol = symbol;
            Name = name;
            LatestTradePrice = latestTradePrice;
            Eps = eps;
            EpsEstimateCurrentYear = epsEstimateCurrentYear;
            EpsEstimateNextYear = epsEstimateNextYear;
            PeRatio = peRatio;
            PegRatio = pegRatio;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "symbol")]
        public string Symbol { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "latestTradePrice")]
        public double? LatestTradePrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eps")]
        public double? Eps { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "epsEstimateCurrentYear")]
        public double? EpsEstimateCurrentYear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "epsEstimateNextYear")]
        public double? EpsEstimateNextYear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "peRatio")]
        public double? PeRatio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pegRatio")]
        public double? PegRatio { get; set; }

    }
}
