// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace InvSys.RuleOne.Api.Client.Proxy.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Rating
    {
        /// <summary>
        /// Initializes a new instance of the Rating class.
        /// </summary>
        public Rating() { }

        /// <summary>
        /// Initializes a new instance of the Rating class.
        /// </summary>
        public Rating(Guid? id = default(Guid?), string companySymbol = default(string), DateTime? date = default(DateTime?), bool? isWonderful = default(bool?))
        {
            Id = id;
            CompanySymbol = companySymbol;
            Date = date;
            IsWonderful = isWonderful;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "companySymbol")]
        public string CompanySymbol { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isWonderful")]
        public bool? IsWonderful { get; set; }

    }
}
