// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace InvSys.Financials.Api.Client.Proxy.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FinancialData
    {
        /// <summary>
        /// Initializes a new instance of the FinancialData class.
        /// </summary>
        public FinancialData() { }

        /// <summary>
        /// Initializes a new instance of the FinancialData class.
        /// </summary>
        public FinancialData(int? id = default(int?), string companySymbol = default(string), int? year = default(int?), string currency = default(string), double? revenue = default(double?), double? eps = default(double?), double? equity = default(double?), double? debt = default(double?), double? cash = default(double?), double? dividends = default(double?), double? roic = default(double?))
        {
            Id = id;
            CompanySymbol = companySymbol;
            Year = year;
            Currency = currency;
            Revenue = revenue;
            Eps = eps;
            Equity = equity;
            Debt = debt;
            Cash = cash;
            Dividends = dividends;
            Roic = roic;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "companySymbol")]
        public string CompanySymbol { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "revenue")]
        public double? Revenue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eps")]
        public double? Eps { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "equity")]
        public double? Equity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "debt")]
        public double? Debt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cash")]
        public double? Cash { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dividends")]
        public double? Dividends { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roic")]
        public double? Roic { get; set; }

    }
}
