// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace InvSys.Identity.Api.Client.Proxy.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class IdentityUserRoleString
    {
        /// <summary>
        /// Initializes a new instance of the IdentityUserRoleString class.
        /// </summary>
        public IdentityUserRoleString() { }

        /// <summary>
        /// Initializes a new instance of the IdentityUserRoleString class.
        /// </summary>
        public IdentityUserRoleString(string userId = default(string), string roleId = default(string))
        {
            UserId = userId;
            RoleId = roleId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roleId")]
        public string RoleId { get; set; }

    }
}
